package edu.psu.jjb24.csjokes.db;

public class DefaultContent {
    public static String[] TITLE = {
            "Base Joke","Java","SQL","Hardware","Testing",
            "C++","Arrays","Recursion","Warnings","Buffers",
            "Strings","Scariest number","Two bytes ","Success",
            "C","Obfuscated Perl","Shakespeare","Windows",
            "RegEx","Concurrent chickens","Programmer spouses",
            "Optimist vs. Pessimist vs.","A scrupulous and honest programmer",
            "Quitting time","Glasses","Hardware","No idea",
            "Stuck","Programmer v. non-programmer","Not a knock-knock joke",
            "A bar","A bar","Poem","SQL developers","UNIX",
            "Recursion","Time v. space ","Donald Knuth",
            "100 buckets of bits"};

    public static String[] SETUP = {
            "Why do programmers always mix up Halloween and Christmas?",
            "\"Knock, knock.\"\n\n\"Who's there?\"\n\nvery long pause...",
            "A SQL query goes into a bar, walks up to two tables and asks, ...",
            "How many programmers does it take to change a light bulb?",
            "A physicist, an engineer and a programmer were in a car driving over a steep alpine pass when the brakes failed. The car was getting faster and faster, they were struggling to get round the corners and once or twice only the feeble crash barrier saved them from crashing down the side of the mountain. They were sure they were all going to die, when suddenly they spotted an escape lane. They pulled into the escape lane, and came safely to a halt.\n\nThe physicist said \"We need to model the friction in the brake pads and the resultant temperature rise, see if we can work out why they failed\".",
            "When your hammer is C++, ...",
            "[\"hip\",\"hip\"]",
            "To truly understand what recursion is, ...",
            "A guy is standing on the corner of the street smoking one cigarette after another. A lady walking by notices him and says\n\n\"Hey, don't you know that those things can kill you? I mean, didn't you see the giant warning on the box?!\"\n\n\"That's OK\" says the guy, puffing casually \"I'm a computer programmer\"\n\n\"So? What's that got to do with anything?\"",
            "I called the janitor the other day to see what he could do about my dingy linoleum floor. He said he would have been happy to loan me a polisher, but that he had not the slightest idea what he had done with it. I told him not to worry about it - that as a programmer ...",
            "These two strings walk into a bar and sit down. The bartender says, \"So what'll it be?\"\n\nThe first string says, \"I think I'll have a beer quag fulk boorg jdk^CjfdLk jk3s d#f67howe%^U r89nvy owmc63^Dz x.xvcu\"",
            "Why is 07 the scariest number?",
            "Two bytes meet. The first byte asks, \"Are you ill?\"",
            "It compiles!",
            "In C, we had to code our own bugs.",
            "How come there is no obfuscated Perl contest?",
            "Question: To be or not to be?",
            "It's been said that if you play a Windows Install DVD backward, you will hear satanic chanting. Worse still, ...",
            "Some people, when confronted with a problem, think, \"I know, I'll use regular expressions!\"",
            "Why did the concurrent chicken cross the road?",
            "Spouse to programmer: \"Buy a stick of butter. If they have eggs, bring 10.\"",
            "Optimist: \"The glass is half full.\"\n\nPessimist: \"The glass is half empty.\"",
            "A scrupulous and honest programmer checked his receipt from a convenience store, and found that they had neglected to charge him for the new junk food taxes recently mandated in New York City. He wrestled with his conscience about returning the money and pointing out the mistake, but, in the end, ...",
            "Q: Why did the programmer quit his job?",
            "Why do java programmers have to wear glasses?",
            "Hardware (def'n):",
            "What sits on your shoulder and goes \"Pieces of 7! Pieces of 7!\"?",
            "Why did the computer scientist get stuck in the shower?",
            "What is the difference between a programmer and a non-programmer?",
            "I was once asked, if I knew any knock-knock jokes.  I said no, but...",
            "Two threads walk into a bar. The bartender looks up and yells, ...",
            "Eight bytes walk into a bar. The bartender asks, \"Can I get you anything?\"",
            "The Programmer's Poem\n\n&lt; &gt; ! * ' ' #\n^ \" ` $ $ -\n ! * = @ $ _ \n % * &lt; &gt; ~ 4\n&; [ ] . . / \n | { , , SYSTEM HALTED",
            "There are only 2 kinds of SQL developers.",
            "UNIX is like eating insects.",
            "If you already know what recursion is, just remember the answer.",
            "The biggest difference between time and space is that ...",
            "Donald Knuth quote, \"Beware of bugs in the above code...",
            "100 buckets of bits on the bus\n100 buckets of bits\ntake one down (short it to ground)"};

    public static String[] PUNCHLINE = {
            "Because Oct 31 == Dec 25!",
            "\"Java.\"",
            "\"Can I join you?\"",
            "None, that is a hardware problem.",
            "The engineer said \"I think I've got a few spanners in the back. I'll take a look and see if I can work out what's wrong\".\n\nThe programmer said \"Why don't we get going again and see if it's reproducible?\"",
            "everything begins to look like a thumb.",
            "(hip hip array!)",
            "you must first understand recursion.",
            "\"We don't care about warnings. We only care about errors.\"",
            "it was not the first time I had experienced a buffer allocation failure due to a memory error.",
            "\"Please excuse my friend,\" the second string says, \"He isn't null-terminated.\"",
            "Because 07 010 011?\n\n Note to self: Perhaps this is funnier in a different base...",
            "The second byte replies, \"No, just feeling a bit off.\"",
            "Let's submit it!",
            "In C++, we can inherit them.",
            "Because everyone would win",
            "Answer: 2B | ^ 2B = FF ",
            "if you play it forwards it installs Windows.",
            "Now they have two problems. - Jamie Zawinski",
            "the other side To to get",
            "Programmer returns with 10 sticks of butter, and says, \"They had eggs.\"",
            "Assembly language programmer: \"The glass is twice as big as it needs to be.\"",
            "he decided it best to make an exception for the sin tax error.",
            "A: Because he didn't get arrays.",
            "Because they don't C#.",
            "The part of a computer that you can kick.",
            "A Parroty Error!",
            "Because the instructions on the shampoo bottle said: Lather, Rinse, Repeat.",
            "The non-programmer thinks a kilobyte is 1000 bytes, while the programmer believes that a kilometer is 1024 meters.",
            "know some !!jokes.  But those are just jokes.",
            "\"Hey! I don't want any conditions race like time last!\"",
            "\"Yeah,\" reply the bytes. \"Make us a double.\"",
            "Waka waka bang splat tick tick hash,\nCaret quote back-tick dollar dollar dash,\nBang splat equal at dollar under-score,\nPercent splat waka waka tilde number four,\nAmpersand bracket bracket dot dot slash,\nVertical-bar curly-bracket comma comma CRASH",
            "- Those who know how COUNT() treats NULLs.\n- Those who don't.\n- Those who don't care.\n",
            "It's all right once you get used to it.",
            "Otherwise, find someone who is standing closer to Douglas Hofstadter than you are, and ask him or her what recursion is.",
            "you cannot reuse time.",
            "I have only proved it correct, not tried it.\"",
            "FF buckets of bits on the bus \nFF buckets of bits on the bus\nFF buckets of bits\ntake one down (short it to ground)\nFE buckets of bits on the bus\n... "};

}
