package edu.psu.jjb24.csjokes.db;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName="jokes")
public class Joke {

    // Note that if id == 0, and this is inserted, an id will be autogenerated
    public Joke(int id, String title, String setup, String punchline, boolean liked) {
        this.id = id;
        this.title = title;
        this.setup = setup;
        this.punchline = punchline;
        this.liked = liked;
    }

    // Assign 0 to id to have it be auto generated
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "rowid")
    public int id;

    @ColumnInfo(name = "title")
    public String title;

    @ColumnInfo(name = "setup")
    public String setup;

    @ColumnInfo(name = "punchline")
    public String punchline;

    @ColumnInfo(name = "liked")
    public boolean liked;
}
